### ISSUE TITLE
Failed to compile with tokio-core v0.1.6

### ISSUE THREAD

**Issue by zonyitoo** [partim/domain#9]
Errors are

```
error[E0432]: unresolved import `tokio_core::channel::Receiver`
  --> /Users/zonyitoo/.cargo/registry/src/github.com-1ecc6299db9ec823/domain-0.1.0/src/resolv/request.rs:33:27
   |
33 | use tokio_core::channel::{Receiver, Sender};
   |                           ^^^^^^^^ Could not find `channel` in `tokio_core`

error[E0432]: unresolved import `tokio_core::channel::Sender`
  --> /Users/zonyitoo/.cargo/registry/src/github.com-1ecc6299db9ec823/domain-0.1.0/src/resolv/request.rs:33:37
   |
33 | use tokio_core::channel::{Receiver, Sender};
   |                                     ^^^^^^ Could not find `channel` in `tokio_core`

error[E0432]: unresolved import `tokio_core::channel::channel`
  --> /Users/zonyitoo/.cargo/registry/src/github.com-1ecc6299db9ec823/domain-0.1.0/src/resolv/service/mod.rs:21:5
   |
21 | use tokio_core::channel::channel;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Could not find `channel` in `tokio_core`
error: the type of this value must be known in this context
  --> /Users/zonyitoo/.cargo/registry/src/github.com-1ecc6299db9ec823/domain-0.1.0/src/resolv/service/sequential.rs:72:61
   |
72 |             State::Reading(mut fut) => fut.take().map(|res| res.2),
   |                                                             ^^^^^

error: the type of this value must be known in this context
  --> /Users/zonyitoo/.cargo/registry/src/github.com-1ecc6299db9ec823/domain-0.1.0/src/resolv/service/sequential.rs:90:21
   |
90 |                     request.set_id(rand::random());
   |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: the type of this value must be known in this context
   --> /Users/zonyitoo/.cargo/registry/src/github.com-1ecc6299db9ec823/domain-0.1.0/src/resolv/service/mod.rs:255:33
    |
255 |                     State::Idle(receiver.into())
    |                                 ^^^^^^^^^^^^^^^
```

**Comment by partim** [comment]
For the 0.1.0 release, I got the dependencies wrong. I assumed that futures and tokio would change the minor release number upon breaking changes. In reality, the 0.1.0 release will only work with `tokio-core` up to 0.1.5 and you will already get deprecation warnings with that version.

I just released 0.2.0 which has the dependencies set more strictly. However, it also contains a complete rewrite of the resolver to match with developments in Tokio land which changed the way `Resolver` works. The new way is better as you can make queries using `Resolver` directly now and necessary code changes should be relatively small.

**Comment by zonyitoo** [comment]
Thanks for quick response! And yes, after small modifications, `v0.2` works well, Thanks!
