### ISSUE TITLE
Could not compile domain

### ISSUE THREAD

**Issue by tianjiaoding** [partim/domain#11]
```
error[E0432]: unresolved import `tokio_core::channel::Receiver`
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/domain-0.1.0/src/resolv/request.rs:33:27
   |
33 | use tokio_core::channel::{Receiver, Sender};
   |                           ^^^^^^^^ Could not find `channel` in `tokio_core`

error[E0432]: unresolved import `tokio_core::channel::Sender`
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/domain-0.1.0/src/resolv/request.rs:33:37
   |
33 | use tokio_core::channel::{Receiver, Sender};
   |                                     ^^^^^^ Could not find `channel` in `tokio_core`

error[E0432]: unresolved import `tokio_core::channel::channel`
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/domain-0.1.0/src/resolv/service/mod.rs:21:5
   |
21 | use tokio_core::channel::channel;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Could not find `channel` in `tokio_core`

error: aborting due to 3 previous errors

error: Could not compile `domain`.

```
The tokio-core downloaded by cargo automatically is v0.1.6.
The environment i'm using is 
`4.8.0-41-generic #44~16.04.1-Ubuntu`
`cargo 0.19.0-nightly (c995e9eb5 2017-03-17)`

**Comment by partim** [comment]
Sorry about that. I got the dependencies wrong in 0.1.0.

There’s version 0.2.0 now. It has breaking changes but I think they are not too bad. Essentially, you can now run queries directly atop a `Resolver`. Is it an option for you to upgrade to that version? I don’t really want to go back and make a 0.1.1 merely fixing the dependencies given that futures and tokio has evolved so much.

**Comment by tianjiaoding** [comment]
Thanks for responding so fast. ^^
I'm actually installing another crate that has the dependency of domain 0.1.0. I don't know if the crate is able to be built on the latest release of domain, but I'll look into that.
BTW, could you kindly provide the version of tokio that can be built with domain 0.1.0?

**Comment by partim** [comment]
With tokio-core 0.1.5 there will be a bunch of deprecation warnings but it will compile. I suppose 0.1.4 will be fine.

There needs to be changes to that other crate in order to work with domain 0.2.0, but they should be reasonably simple. If you need help, let me know. I am more than happy to be of assistance.
